name: Sync with Original Author

on:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨 2 点自动检查原作者更新
  workflow_dispatch: # 同时也允许你手动点按钮同步

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    if: github.repository == '你的用户名/clawInstaller' # 替换成你的路径
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: diandianti/clawInstaller # 原作者仓库
          upstream_branch: main
          target_branch: main
          test_mode: false
